# Generated by Django 6.0.1 on 2026-05-03 16:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('complaints', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='complaint',
            name='admin_response',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='complaint',
            name='category',
            field=models.CharField(choices=[('Service Quality', 'Service Quality'), ('Service Delay', 'Service Delay'), ('Billing Issue', 'Billing Issue'), ('Staff Behavior', 'Staff Behavior'), ('Other', 'Other')], default='Other', max_length=50),
        ),
        migrations.AddField(
            model_name='complaint',
            name='service_id',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='complaint',
            name='status',
            field=models.CharField(choices=[('Pending', 'Pending'), ('In Review', 'In Review'), ('Resolved', 'Resolved')], default='Pending', max_length=20),
        ),
    ]
